# Generated by Django 2.0.1 on 2021-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200520_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='sex',
            field=models.IntegerField(default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='rate',
            name='work',
            field=models.IntegerField(default=5, verbose_name='工作类别'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.IntegerField(choices=[(1, 'IT类'), (2, '设计类'), (3, '销售类'), (4, '文秘'), (5, '学生')], default=5, verbose_name='工作类别'),
        ),
    ]
