# Generated by Django 2.0.1 on 2021-04-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210404_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.IntegerField(choices=[(1, '中国'), (2, '美国'), (3, '英国'), (4, '法国'), (5, '德国'), (6, '日本'), (7, '意大利')], default=1, verbose_name='国家'),
        ),
    ]
