# Generated by Django 2.0.1 on 2021-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210404_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='address',
            field=models.IntegerField(default=1, verbose_name='国家'),
        ),
    ]
