# Generated by Django 2.0.1 on 2021-04-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210408_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shuxin',
            field=models.CharField(max_length=32, verbose_name='属性'),
        ),
    ]
