# Generated by Django 2.0.1 on 2021-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210408_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shuxin',
        ),
        migrations.AddField(
            model_name='user',
            name='shu',
            field=models.CharField(default='aaa', max_length=32, verbose_name='属性'),
        ),
    ]
